### ISSUE TITLE
💡 Replacement for react-native-camera

### ISSUE THREAD

**Issue by MarcoScabbiolo** [margelo/react-native-vision-camera#56] opened 2021-03-12 18:51 UTC
## Question

Hi @mrousavy , what do you think about this library being a continuation of `react-native-camera`? I'm currently working on a revamped version 4 of `react-native-camera` and all the changes to the code are very similar to what this library already has.
The underlying API of this library is really clean and although `react-native-camera` offers some more customization, options and parameters, it does so with a very clumsy API. It is really hard to get to a clean implementation from `react-native-camera` 3 and the implementation in `react-native-vision-camera` is already clean and you are having a much faster development pace. Your extension solution looks very promising, and although there might be some use cases frame processing won't be able to cover like live streaming the camera output with native-grade performance, all of the existing use cases (Bar/QR code scanning, AI stuff) can be achieved.

CC: @cristianoccazinsp @MateusAndrade @sibelius

**Comment by cristianoccazinsp** [comment] 2021-03-12 18:59
It's on our company's todo list to give this library a try.  We are specifically worried about Android, due to CameraX/Camera2 being extremely slow and we need quick pictures without the need to wait for a focus operation as it does the camera by default.

Secondly, we also need QR scanning capabilities, so that would be a must for us.

Lastly, I believe this library is strongly `hooks` oriented, but our main code base is class/refs oriented, so that would mean some work on our end to be even able to use this library.

**Comment by MarcoScabbiolo** [comment] 2021-03-12 19:11
> It's on our company's todo list to give this library a try. We are specifically worried about Android, due to CameraX/Camera2 being extremely slow and we need quick pictures without the need to wait for a focus operation as it does the camera by default.

CameraX is still unfinished but will be the definitive API for Android, there is no escaping it.

> Secondly, we also need QR scanning capabilities, so that would be a must for us.

Same here, we can start working on it when Frame Processing is done

> Lastly, I believe this library is strongly hooks oriented, but our main code base is class/refs oriented, so that would mean some work on our end to be even able to use this library.

Hooks are a one-way trip, you'll love them. Using hooks in class components is very similar to using HOCs.

**Comment by mrousavy** [comment] 2021-03-12 19:31
Hey @MarcoScabbiolo & @cristianoccazinsp!

> what do you think about this library being a continuation of react-native-camera?

I'd dig that! 🎉 

> although react-native-camera offers some more customization

like what? I'm still not entirely done with all the features, but it's shippable with many features as it is now. Android is missing some nice to haves, but I'm working on that - most of that is limited by CameraX. And a lot of other stuff will be possible with frame processors. (https://github.com/cuvent/react-native-vision-camera/pull/2)

I have to say I didn't invest a lot of time in trying to get react-native-camera working for us, but I noticed that we expected more features than that library could deliver. Correct me if I'm wrong, but I think you couldn't e.g. choose a custom format and select a custom FPS range. 🤔 

> and although there might be some use cases frame processing won't be able to cover like live streaming the camera output with native-grade performance

I'm still positive that I can create a `jsi::HostObject` from the frame without copying it, so I I'd say native-grade performance for livestreaming is definitely possible. That's just going to be another frame processor plugin, for WebRTC or something. Just like how Reanimated animations are running in 60 FPS. **Don't quote me on that though!** All of that is WIP.

I'm really invested in this library and with the frame processors it's going to be very versatile and extensible. The only thing that's still bothering me is the CameraX library since that has by far less features than the iOS AVCam. But it is still in an early phase, and apparently is the future of Android Cameras, so I'd say I bet on the right horse. I have a few tickets open in google's issue tracker which are being worked on by the google team, that should add a few missing features on the android side.

@cristianoccazinsp 

> We are specifically worried about Android, due to CameraX/Camera2 being extremely slow and we need quick pictures without the need to wait for a focus operation as it does the camera by default.

CameraX is based on Camera2, so it is not really slower than that. I wouldn't say Camera2 is slow, it's just how cameras are on Android. Also, I will rewrite the `takePicture` func in JSI, so that you get an Image instance (`UIImage`/`Bitmap` HostObject) returned immediately, without any File IO overhead. Just like on native. (Right now it takes the picture, writes it to a file, and then reads the file in JS again) This would require an additional library that can render those images in a View, so that's on my list too.

> Lastly, I believe this library is strongly hooks oriented, but our main code base is class/refs oriented, so that would mean some work on our end to be even able to use this library.

It is not, the hooks are only wrappers for the imperative API calls such as `Camera.getAvailableCameraDevices()`. You can also very easily call that in a class component. Hooks are just a bit less code (by design). Use whatever you prefer, but I love hooks.

**Comment by mrousavy** [comment] 2021-03-12 19:38
To add to that; With frame processors all of the QR code detection, MLKit/OpenCV AI, AR, Livestreaming with WebRTC etc code doesn't have to be maintained in this library because with the frame processor plugin approach all of that is lifted into separate libraries - this means cleaner code, faster release cycles, and more extensibility. Everyone can create plugins 🤗

**Comment by MarcoScabbiolo** [comment] 2021-03-12 19:48
>I'd dig that! 🎉

:heart:

>> although react-native-camera offers some more customization

>like what? I'm still not entirely done with all the features,

Most of the features are not properly documented but are implemented, like focus, white balance, exposure, picture/video output resolution, exif data, and more. Of course the implementation varies a lot between iOS and Android.


About extensibility, I couldn't think of a best solution that the one you're presenting. I wasn't saying Frame Processing won't support live streaming, it's just a way to say that there might be use cases that require more extensibiliy on the native side than a succession of camera frames, but luckily that's not relevant right now.


--------

Let's wait for you to finish the Frame Processing feature, I can help with the QR code reading plugin. If we get that done and the preview/picture/video use cases are stable, I think we can make it official.

**Comment by mrousavy** [comment] 2021-05-02 09:18
Frame Processors are ready for iOS. I think I'll merge that first, and implement Android shortly after.

**Comment by mrousavy** [comment] 2021-05-06 14:08
Merged, released in [**2.0.0**](https://github.com/cuvent/react-native-vision-camera/releases/tag/v2.0.0).

**Closed as completed** 2021-05-06 14:30 UTC
Labels: 💭 question
